### ISSUE TITLE
Crash when using more than 3 pages

### ISSUE THREAD

**Issue by resignedScientist** [TangoAgency/material-intro-screen#108]
It crashes when you use more than 3 pages, scroll to the last page, back to the first page and then to the next page. It is reproducable!

`04-27 08:47:27.202 2199-2199/com.laudien.p1xelfehler.batterywarner_pro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.laudien.p1xelfehler.batterywarner_pro, PID: 2199
                                                                                         android.view.InflateException: Binary XML file line #25: Error inflating class fragment
                                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                             at com.laudien.p1xelfehler.batterywarner.Activities.IntroActivity.PreferencesSlide.onCreateView(PreferencesSlide.java:21)
                                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                             at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                                             at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                             at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
                                                                                             at agency.tango.materialintroscreen.MaterialIntroActivity$5.onClick(MaterialIntroActivity.java:219)
                                                                                             at android.view.View.performClick(View.java:4438)
                                                                                             at android.view.View$PerformClick.run(View.java:18422)
                                                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                                          Caused by: java.lang.IllegalArgumentException: Binary XML file line #25: Duplicate id 0x7f0f00d7, tag null, or parent id 0xffffffff with another fragment for com.laudien.p1xelfehler.batterywarner.Activities.SettingsActivity.SettingsFragment
                                                                                             at android.app.Activity.onCreateView(Activity.java:4791)
                                                                                             at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36)
                                                                                             at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
                                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                             at com.laudien.p1xelfehler.batterywarner.Activities.IntroActivity.PreferencesSlide.onCreateView(PreferencesSlide.java:21) 
                                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
                                                                                             at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984) 
                                                                                             at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626) 
                                                                                             at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166) 
                                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1268) 
                                                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668) 
                                                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630) 
                                                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611) 
                                                                                             at agency.tango.materialintroscreen.MaterialIntroActivity$5.onClick(MaterialIntroActivity.java:219) 
                                                                                             at android.view.View.performClick(View.java:4438) 
                                                                                             at android.view.View$PerformClick.run(View.java:18422) 
                                                                                             at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                             at dalvik.system.NativeStart.main(Native Method) `

**Comment by radzio** [comment]
Hi! I don't think that this is library fault. Check your stack trace:

`Caused by: java.lang.IllegalArgumentException: Binary XML file line #25: Duplicate id 0x7f0f00d7, tag null, or parent id 0xffffffff with another fragment for com.laudien.p1xelfehler.batterywarner.Activities.SettingsActivity.SettingsFragment at android.app.Activity.onCreateView(Activity.java:4791)`

**Comment by radzio** [comment]
@P1xelfehler  can you check my previous comment and try to reproduce this error using *material-intro-screen* [demo app](https://github.com/TangoAgency/material-intro-screen/tree/master/app)?

**Comment by resignedScientist** [comment]
Okay, the demo app does not crash when i do that.

So it must be my own fault, i am sorry.

**Comment by radzio** [comment]
@P1xelfehler no problem :), good luck!

**Comment by resignedScientist** [comment]
I analysed that a bit and found out, why this happened:

It happens, when you use a fragment inside the slide layout and give it an id or tag.
If you give an id to the root layout instead, it does not crash anymore!

But i don't know exactly, why this happens.
