### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by abreuretto** [TangoAgency/material-intro-screen#148]
I use Tango Agency : 
implementation 'agency.tango.android:material-intro-screen:0.0.5'
and I received thid message:

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2830)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2905)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1606)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:169)
  at android.app.ActivityThread.main (ActivityThread.java:6595)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: 
  at android.app.Activity.onCreate (Activity.java:992)
  at android.support.v4.app.SupportActivity.onCreate (SupportActivity.java:66)
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:285)
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:84)
  at agency.tango.materialintroscreen.MaterialIntroActivity.onCreate (MaterialIntroActivity.java:73)
  at abreuretto.com.adsappdetector.IntroActivity.onCreate (IntroActivity.java:20)
  at android.app.Activity.performCreate (Activity.java:7016)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2783)

**Comment by dsdebastiani** [comment]
I received same error is two devices with Android: 8.0.0

``` java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)```

**Comment by charlesawoodson** [comment]
I'm currently having the same problem as stated above, has anyone resolved or figured out a work around solution?

**Comment by ognjenns** [comment]
workaround:
https://stackoverflow.com/questions/46992843/interstitial-admob-ads-illegalstateexception-only-fullscreen-activities-can-r/48665610#48665610
