### ISSUE TITLE
Not compatible with AndroidX

### ISSUE THREAD

**Issue by frapeti** [TangoAgency/material-intro-screen#169]
java.lang.IllegalAccessError: Method 'void androidx.viewpager.widget.PagerAdapter.setViewPagerObserver(android.database.DataSetObserver)' is inaccessible to class 'androidx.core.view.CustomViewPager' (declaration of 'androidx.core.view.CustomViewPager' appears in /data/app/com.myapp-kpPRJwiysP3ALIy5WkActg==/base.apk!classes2.dex)
        at androidx.core.view.CustomViewPager.setAdapter(CustomViewPager.java:530)
        at agency.tango.materialintroscreen.MaterialIntroActivity.onCreate(MaterialIntroActivity.java:94)

**Comment by SpeedFire0** [comment]
Confirm that! 

2018-08-28 10:21:31.580 11301-11301/ru.speedfire.flycontrolcenter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.speedfire.flycontrolcenter, PID: 11301
    java.lang.IllegalAccessError: Method 'void androidx.viewpager.widget.PagerAdapter.setViewPagerObserver(android.database.DataSetObserver)' is inaccessible to class 'androidx.core.view.CustomViewPager' (declaration of 'androidx.core.view.CustomViewPager' appears in /data/app/ru.speedfire.flycontrolcenter-A3lZfc55BE8x8n96VqR1rQ==/split_lib_slice_0_apk.apk)
        at androidx.core.view.CustomViewPager.setAdapter(CustomViewPager.java:530)
        at agency.tango.materialintroscreen.MaterialIntroActivity.onCreate(MaterialIntroActivity.java:94)
        at ru.speedfire.flycontrolcenter.intro.IntroActivity.onCreate(IntroActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by SpeedFire0** [comment]
It seems that this library is not supported anymore.
I've changed my intro screen to this one https://github.com/apl-devs/AppIntro
It's AndroidX compatible.

**Comment by vedprakashwagh** [comment]
Yes this library is androidx compatible, the way he's added the class CustomViewPager into android.support.v4.view package makes android studio confuses the android studio while migrating, simple fix is to just drop the CustomViewPager class into different package which does not have support package name

**Comment by frapeti** [comment]
https://github.com/MiAutobus/material-intro-screen/commit/663ece31c0cabd0809f74843a7c12a3d8301c62a

**Comment by DreierF** [comment]
I created a fork of this library since the author seems to no longer maintain it and published an AndroidX compatible version to maven central: https://github.com/DreierF/material-intro-screen

**Comment by saddahussain** [comment]
@DreierF Highly appreciate your work. Keep up the good work.

**Comment by zjxuzhj** [comment]
@DreierF thank you

**Comment by Sanaebadi97** [comment]
@DreierF tnx 
I used 
`    implementation 'io.github.dreierf:material-intro-screen:0.0.6'`

and solve my problem

**Comment by BhoomiKhan** [comment]
> I created a fork of this library since the author seems to no longer maintain it and published an AndroidX compatible version to maven central: https://github.com/DreierF/material-intro-screen

thank you dreierF your solution helped me a lot.

**Comment by guriosam** [comment]
> 
> 
> I created a fork of this library since the author seems to no longer maintain it and published an AndroidX compatible version to maven central: https://github.com/DreierF/material-intro-screen

You are a god, just saved my day!

**Comment by umutgultekn** [comment]
@DreierF thank u bro. It's work well.
