### ISSUE TITLE
Orientation Change: NullPointerException

### ISSUE THREAD

**Issue by Scrounger** [TangoAgency/material-intro-screen#40]
After orientation change (not on first slide) it thorws a NullPointerException:

In Manifest the Intro Activity is declared as:

```
        <activity
            android:name=".Activties.IntroActivity"
            android:theme="@style/Theme.Intro"
            android:launchMode="singleTask"/>
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{myApp/myApp.Activties.IntroActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                             at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                             at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:148)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                             at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
                                                             at agency.tango.materialintroscreen.listeners.MessageButtonBehaviourOnPageSelected.showMessageButton(MessageButtonBehaviourOnPageSelected.java:57)
                                                             at agency.tango.materialintroscreen.listeners.MessageButtonBehaviourOnPageSelected.pageSelected(MessageButtonBehaviourOnPageSelected.java:40)
                                                             at agency.tango.materialintroscreen.listeners.ViewBehavioursOnPageChangeListener.onPageSelected(ViewBehavioursOnPageChangeListener.java:61)
                                                             at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1939)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:632)
                                                             at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1454)
                                                             at android.view.View.dispatchRestoreInstanceState(View.java:14746)
                                                             at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
                                                             at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                             at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                             at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                             at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                             at android.view.View.restoreHierarchyState(View.java:14724)
                                                             at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
                                                             at android.app.Activity.onRestoreInstanceState(Activity.java:1004)
                                                             at android.app.Activity.performRestoreInstanceState(Activity.java:959)
                                                             at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                             at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                             at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:148) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by Scrounger** [comment]
I have done some more testing. This only happens if you using 
`new MessageButtonBehaviour`

**Comment by zlsa** [comment]
Is this fixed in master?

**Comment by bezmian** [comment]
Not yet
